[project]
name = "baby-feeding-diaper-grapher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datetime>=5.5",
    "matplotlib>=3.10.6",
    "pandas>=2.3.2",
]
